//
// AuthError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AuthError: JSONEncodable {
    /** Short error identifier */
    public var error: String?
    /** Extended error description */
    public var errorDescription: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["error"] = self.error
        nillableDictionary["error_description"] = self.errorDescription
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
