//
// AwardsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class AwardsData: JSONEncodable {
    /** Award name */
    public var title: String?
    public var nominee: [AwardData]?
    public var winner: [AwardData]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["title"] = self.title
        nillableDictionary["nominee"] = self.nominee?.encodeToJSON()
        nillableDictionary["winner"] = self.winner?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
