//
// Card.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Basic Dive data unit, represents an item of a given category */
open class Card: JSONEncodable {
    public enum TypeOfCard: String { 
        case RAWMOVIE_ENUMMOVIE = "'{raw=movie, enum=Movie}'"
        case RAWSERIE_ENUMSERIE = "'{raw=serie, enum=Serie}'"
        case RAWPERSON_ENUMPERSON = "'{raw=person, enum=Person}'"
        case RAWCHARACTER_ENUMCHARACTER = "'{raw=character, enum=Character}'"
        case RAWVEHICLE_ENUMVEHICLE = "'{raw=vehicle, enum=Vehicle}'"
        case RAWFASHION_ENUMFASHION = "'{raw=fashion, enum=Fashion}'"
        case RAWLOCATION_ENUMLOCATION = "'{raw=location, enum=Location}'"
        case RAWHISTORIC_ENUMHISTORIC = "'{raw=historic, enum=Historic}'"
        case RAWTRIVIA_ENUMTRIVIA = "'{raw=trivia, enum=Trivia}'"
        case RAWQUOTE_ENUMQUOTE = "'{raw=quote, enum=Quote}'"
        case RAWOST_ENUMOST = "'{raw=ost, enum=Ost}'"
        case RAWHOME_ENUMHOME = "'{raw=home, enum=Home}'"
        case RAWTECHNOLOGY_ENUMTECHNOLOGY = "'{raw=technology, enum=Technology}'"
        case RAWART_ENUMART = "'{raw=art, enum=Art}'"
        case RAWSONG_ENUMSONG = "'{raw=song, enum=Song}'"
        case RAWLOOK_ENUMLOOK = "'{raw=look, enum=Look}'"
        case RAWWEAPON_ENUMWEAPON = "'{raw=weapon, enum=Weapon}'"
        case RAWLEISURE_SPORT_ENUMLEISURE_SPORT = "'{raw=leisure_sport, enum=LeisureSport}'"
        case RAWHEALTH_BEAUTY_ENUMHEALTH_BEAUTY = "'{raw=health_beauty, enum=HealthBeauty}'"
        case RAWFOOD_DRINK_ENUMFOOD_DRINK = "'{raw=food_drink, enum=FoodDrink}'"
        case RAWFAUNA_FLORA_ENUMFAUNA_FLORA = "'{raw=fauna_flora, enum=FaunaFlora}'"
        case RAWBUSINESS_ENUMBUSINESS = "'{raw=business, enum=Business}'"
        case RAWREFERENCE_ENUMREFERENCE = "'{raw=reference, enum=Reference}'"
        case RAWCHAPTER_ENUMCHAPTER = "'{raw=chapter, enum=Chapter}'"
    }
    /** Card unique identifier */
    public var cardId: String?
    /** Card version for a given movie and scene */
    public var version: String?
    /** Card type */
    public var typeOfCard: TypeOfCard?
    /** Card content locale */
    public var locale: String?
    /** Card title */
    public var title: String?
    /** Card subtitle (might be empty) */
    public var subtitle: String?
    public var image: ImageData?
    public var info: [CardContainer]?
    public var relations: [RelationModule]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["card_id"] = self.cardId
        nillableDictionary["version"] = self.version
        nillableDictionary["typeOfCard"] = self.typeOfCard?.rawValue
        nillableDictionary["locale"] = self.locale
        nillableDictionary["title"] = self.title
        nillableDictionary["subtitle"] = self.subtitle
        nillableDictionary["image"] = self.image?.encodeToJSON()
        nillableDictionary["info"] = self.info?.encodeToJSON()
        nillableDictionary["relations"] = self.relations?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
