//
// CatalogSync.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Dive interactive capabilities of this catalog item */
open class CatalogSync: JSONEncodable {
    /** Indicates if this catalog item can be synchronized */
    public var isSynchronizable: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["is_synchronizable"] = self.isSynchronizable
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
