//
// CatalogData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CatalogData: JSONEncodable {
    /** URL of an additional background image for this catalog element */
    public var backgroundImage: String?
    /** Name of the director */
    public var director: String?
    /** List of genres of this catalog entry */
    public var genres: [String]?
    /** Original language title */
    public var originalTitle: String?
    /** Length of the movie or chapter, or average length of serie chapters, in minutes */
    public var runtime: Int32?
    /** Year of production */
    public var year: Int32?
    /** Index of the chapter inside its season (only for content_type&#x3D;chapter) */
    public var chapterIndex: Int32?
    /** Index of the season where the chapter belongs (only for content_type&#x3D;chapter) */
    public var seasonIndex: Int32?
    public var sync: CatalogSync?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["background_image"] = self.backgroundImage
        nillableDictionary["director"] = self.director
        nillableDictionary["genres"] = self.genres?.encodeToJSON()
        nillableDictionary["original_title"] = self.originalTitle
        nillableDictionary["runtime"] = self.runtime?.encodeToJSON()
        nillableDictionary["year"] = self.year?.encodeToJSON()
        nillableDictionary["chapter_index"] = self.chapterIndex?.encodeToJSON()
        nillableDictionary["season_index"] = self.seasonIndex?.encodeToJSON()
        nillableDictionary["sync"] = self.sync?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
