//
// ChannelStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ChannelStatus: JSONEncodable {
    /** Provided channel ID */
    public var channelId: String?
    /** True if channel is broadcasting synchronizable content, False otherwise */
    public var ready: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["channel_id"] = self.channelId
        nillableDictionary["ready"] = self.ready
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
