//
// ImageData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Linked image URL and additional information */
open class ImageData: JSONEncodable {
    /** Image thumbnail URL */
    public var thumb: String?
    /** Full size image URL */
    public var full: String?
    /** Image anchor X axis (percent) */
    public var anchorX: Double?
    /** Image anchor Y axis (percent) */
    public var anchorY: Double?
    public var source: SourceData?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["thumb"] = self.thumb
        nillableDictionary["full"] = self.full
        nillableDictionary["anchor_x"] = self.anchorX
        nillableDictionary["anchor_y"] = self.anchorY
        nillableDictionary["source"] = self.source?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
