//
// MapData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class MapData: JSONEncodable {
    /** Value of the location latitude, in decimal format degrees */
    public var latitude: Float?
    /** Value of the location longitude, in decimal format degrees */
    public var longitude: Float?
    /** Zoom value, defines the height coordinate over the given location */
    public var zoom: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["zoom"] = self.zoom?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
