//
// MovieStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class MovieStatus: JSONEncodable {
    /** Provided client movie ID */
    public var movieId: String?
    /** True if movie can be synchronized via this API, False otherwise. */
    public var ready: Bool?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["movie_id"] = self.movieId
        nillableDictionary["ready"] = self.ready
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
