//
// RelationModule.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Relation modules provide lists of cards related to the current one. It&#39;s contents depend on the module &#39;type&#39; attribute */
open class RelationModule: JSONEncodable {
    public enum TypeOfRelation: String { 
        case RAWSINGLE_ENUMSINGLE = "'{raw=single, enum=Single}'"
        case RAWDUPLE_ENUMDUPLE = "'{raw=duple, enum=Duple}'"
    }
    /** Relation module type, defines the contained data structure */
    public var typeOfRelation: TypeOfRelation?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["typeOfRelation"] = self.typeOfRelation?.rawValue
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
