//
// SeasonsChapters.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SeasonsChapters: JSONEncodable {
    /** Index of the chapter inside this season */
    public var chapterIndex: Int32?
    /** ID of the chapter card */
    public var cardId: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["chapter_index"] = self.chapterIndex?.encodeToJSON()
        nillableDictionary["card_id"] = self.cardId
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
