//
// SeasonsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SeasonsData: JSONEncodable {
    /** Index of the season */
    public var seasonIndex: Int32?
    /** Comma separated list of season creators */
    public var creators: String?
    public var image: ImageData?
    /** Year of production of this season */
    public var year: Int32?
    /** List of season chapters */
    public var chapters: [SeasonsChapters]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["season_index"] = self.seasonIndex?.encodeToJSON()
        nillableDictionary["creators"] = self.creators
        nillableDictionary["image"] = self.image?.encodeToJSON()
        nillableDictionary["year"] = self.year?.encodeToJSON()
        nillableDictionary["chapters"] = self.chapters?.encodeToJSON()
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
